//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicDepartment()
        {
            this.DiscountCategory = new HashSet<DiscountCategory>();
            this.DMCM = new HashSet<DMCM>();
            this.Employee = new HashSet<Employee>();
            this.EducationalLevelDepartment = new HashSet<EducationalLevelDepartment>();
        }
    
        public int AcaDeptID { get; set; }
        public string AcaDepartmentName { get; set; }
        public string AcaAcronym { get; set; }
        public bool IsAcad { get; set; }
        public string GLCode { get; set; }
        public Nullable<int> EmployeeDivisionID { get; set; }
        public string TempPYDeptMigration { get; set; }
        public string QNEProjectCode { get; set; }
        public string MainDeptID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCategory> DiscountCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMCM> DMCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual Project Project { get; set; }
        public virtual AcademicDepartment AcademicDepartment1 { get; set; }
        public virtual AcademicDepartment AcademicDepartment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalLevelDepartment> EducationalLevelDepartment { get; set; }
    }
}
