//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alpha4Payment
    {
        public int Id { get; set; }
        public Nullable<int> Alpha4Id { get; set; }
        public string OrNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> PaymentId { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
