//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alpha4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alpha4()
        {
            this.Alpha4Payment = new HashSet<Alpha4Payment>();
        }
    
        public int Id { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string LastName { get; set; }
        public string BADate { get; set; }
        public decimal Amount { get; set; }
        public int EducLevelId { get; set; }
        public string Remarks { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
    
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alpha4Payment> Alpha4Payment { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
    }
}
