//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alpha4
    {
        public int Id { get; set; }
        public string StudentNo { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string LastName { get; set; }
        public string BADate { get; set; }
        public decimal Amount { get; set; }
        public int EducLevelId { get; set; }
        public string Remarks { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
    
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual Student Student { get; set; }
    }
}
