//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARSMSLog
    {
        public int ARSMSLogID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string MobileNo { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> MessageTypeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
    }
}
