//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public long AssessmentID { get; set; }
        public Nullable<int> Student_SectionID { get; set; }
        public Nullable<int> FeeID { get; set; }
        public string Description { get; set; }
        public string FeeType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> DiscountAmount { get; set; }
        public bool Locked { get; set; }
        public Nullable<decimal> TuitionRate { get; set; }
        public Nullable<decimal> TuitionDiscountRate { get; set; }
        public Nullable<decimal> TotalUnits { get; set; }
        public Nullable<decimal> MaxUnit { get; set; }
    
        public virtual Student_Section Student_Section { get; set; }
        public virtual Fee Fee { get; set; }
    }
}
