//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSchedule_ReAss
    {
        public int AssessmentSchedule_ReAssID { get; set; }
        public Nullable<int> StudentSection_ReAssID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string SubjectCode { get; set; }
        public Nullable<double> Unit { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public string Days { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Student_Section_ReAss Student_Section_ReAss { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
