//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPaymentDate_ReAss
    {
        public int AssessmentPaymentDate_ReAssID { get; set; }
        public Nullable<int> StudentSectionReAssID { get; set; }
        public Nullable<int> PaycodeID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Student_Section_ReAss Student_Section_ReAss { get; set; }
        public virtual Paycode Paycode { get; set; }
    }
}
