//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPaymentDate
    {
        public int AssessmentPaymentDateID { get; set; }
        public Nullable<int> StudentSectionID { get; set; }
        public Nullable<int> PaycodeID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> PaymodeID { get; set; }
    
        public virtual Paymode Paymode { get; set; }
        public virtual Student_Section Student_Section { get; set; }
        public virtual Paycode Paycode { get; set; }
    }
}
