//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackaccountDMCM
    {
        public int BackAccountDMCMID { get; set; }
        public int BackaccountID { get; set; }
        public int DMCMID { get; set; }
    
        public virtual BackAccount BackAccount { get; set; }
        public virtual DMCM DMCM { get; set; }
    }
}
