//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChartOfAccounts()
        {
            this.DiscountCategory = new HashSet<DiscountCategory>();
            this.DiscountType = new HashSet<DiscountType>();
            this.DiscountType1 = new HashSet<DiscountType>();
            this.DMCM = new HashSet<DMCM>();
            this.Fee = new HashSet<Fee>();
            this.Paycode = new HashSet<Paycode>();
            this.SubChartOfAccounts = new HashSet<SubChartOfAccounts>();
            this.EducationalLevel = new HashSet<EducationalLevel>();
        }
    
        public int AcctID { get; set; }
        public string AcctNo { get; set; }
        public string AcctName { get; set; }
        public Nullable<int> AcctType { get; set; }
        public Nullable<bool> Sl_flag { get; set; }
        public Nullable<bool> Dept_flag { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> SYID { get; set; }
        public string QNEAccountCode { get; set; }
    
        public virtual QNEGLAccount QNEGLAccount { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCategory> DiscountCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountType> DiscountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountType> DiscountType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMCM> DMCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paycode> Paycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubChartOfAccounts> SubChartOfAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalLevel> EducationalLevel { get; set; }
    }
}
