//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeferredIncome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeferredIncome()
        {
            this.DeferredIncomeFee = new HashSet<DeferredIncomeFee>();
        }
    
        public int Id { get; set; }
        public int PeriodId { get; set; }
        public int AcademicDepartmentId { get; set; }
        public System.DateTime DateGenerated { get; set; }
        public System.DateTime PostingDate { get; set; }
        public int GeneratedBy { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsFinal { get; set; }
        public int NthMonth { get; set; }
        public int NoOfMonths { get; set; }
    
        public virtual AcademicDepartment AcademicDepartment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeferredIncomeFee> DeferredIncomeFee { get; set; }
    }
}
