//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountCategory()
        {
            this.Discount = new HashSet<Discount>();
            this.DiscountType = new HashSet<DiscountType>();
            this.DiscountType1 = new HashSet<DiscountType>();
        }
    
        public int DiscountCategoryID { get; set; }
        public string DiscountCategory1 { get; set; }
        public Nullable<int> AcademicDepartmentID { get; set; }
        public Nullable<int> AcctID { get; set; }
        public Nullable<int> SubAcctID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountType> DiscountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountType> DiscountType1 { get; set; }
        public virtual ChartOfAccounts ChartOfAccounts { get; set; }
        public virtual SubChartOfAccounts SubChartOfAccounts { get; set; }
        public virtual AcademicDepartment AcademicDepartment { get; set; }
    }
}
