//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountTypeDetail
    {
        public int DicountTypeDetailID { get; set; }
        public Nullable<int> DiscountTypeID { get; set; }
        public Nullable<int> FeeNameID { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
    
        public virtual DiscountType DiscountType { get; set; }
        public virtual FeeName FeeName { get; set; }
    }
}
