//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscountType()
        {
            this.Discount = new HashSet<Discount>();
            this.DiscountTypeDetail = new HashSet<DiscountTypeDetail>();
        }
    
        public int DiscountTypeID { get; set; }
        public Nullable<double> PercentForMisc { get; set; }
        public Nullable<double> PercentForTuition { get; set; }
        public Nullable<double> PercentForTotal { get; set; }
        public Nullable<bool> MiscCharge { get; set; }
        public string DiscountTypeName { get; set; }
        public Nullable<double> VoucherValue { get; set; }
        public Nullable<int> AcctIDVoucher { get; set; }
        public Nullable<int> AcctIDPercent { get; set; }
        public Nullable<int> VoucherCategoryID { get; set; }
        public Nullable<int> DiscountCategoryID { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public Nullable<int> SLAID { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        public virtual DiscountCategory DiscountCategory { get; set; }
        public virtual DiscountCategory DiscountCategory1 { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountTypeDetail> DiscountTypeDetail { get; set; }
        public virtual ChartOfAccounts ChartOfAccounts { get; set; }
        public virtual ChartOfAccounts ChartOfAccounts1 { get; set; }
        public virtual SubChartOfAccounts SubChartOfAccounts { get; set; }
    }
}
