//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount()
        {
            this.DmcmDiscountDetail = new HashSet<DmcmDiscountDetail>();
        }
    
        public int DiscountID { get; set; }
        public int StudentID { get; set; }
        public int PeriodID { get; set; }
        public int DiscountTypeID { get; set; }
        public Nullable<bool> VoucherAfterDiscount { get; set; }
        public string CVLRN { get; set; }
        public Nullable<int> DiscountCategoryID { get; set; }
        public Nullable<double> MaxUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DmcmDiscountDetail> DmcmDiscountDetail { get; set; }
        public virtual DiscountType DiscountType { get; set; }
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
        public virtual DiscountCategory DiscountCategory { get; set; }
    }
}
