//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DmcmDiscountDetail
    {
        public int Id { get; set; }
        public int DmcmId { get; set; }
        public int FeeId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual DMCM DMCM { get; set; }
        public virtual Fee Fee { get; set; }
    }
}
