//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Downpayment
    {
        public int EducationalLevelId { get; set; }
        public int PaymentModeId { get; set; }
        public Nullable<bool> IsPercent { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> DecimalOnLastPayment { get; set; }
    
        public virtual Paymode Paymode { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
    }
}
