//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownpaymentPercent
    {
        public int EducationalLevelId { get; set; }
        public int PaymodeId { get; set; }
        public Nullable<decimal> Downpayment { get; set; }
        public bool ForTotal { get; set; }
        public int NoOfPayments { get; set; }
    
        public virtual Paymode Paymode { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
    }
}
