//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalLevelDepartment
    {
        public int Id { get; set; }
        public int EducationalLevelId { get; set; }
        public int AcademicDepartmentId { get; set; }
    
        public virtual AcademicDepartment AcademicDepartment { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
    }
}
