//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Payment = new HashSet<Payment>();
            this.Payment1 = new HashSet<Payment>();
            this.Payment2 = new HashSet<Payment>();
            this.Faculty = new HashSet<Faculty>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeNo { get; set; }
        public string Title { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> EmployeeDepartmentID { get; set; }
        public Nullable<int> FacultyAreaID { get; set; }
        public Nullable<int> EmployeeStatusID { get; set; }
        public Nullable<int> EmployeeDesignation { get; set; }
        public Nullable<int> EmployeePositionID { get; set; }
        public Nullable<int> EmployeeLevelID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DatePermanency { get; set; }
        public Nullable<System.DateTime> DateEndContract { get; set; }
        public string ReasonForLeaving { get; set; }
        public string OtherReasonForLeaving { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<System.DateTime> DateRetired { get; set; }
        public string ResidentialAddress { get; set; }
        public Nullable<int> ResidentialAreaID { get; set; }
        public Nullable<int> ResidentialZipCodeID { get; set; }
        public string ProvincialAddress { get; set; }
        public Nullable<int> ProvincialAreaID { get; set; }
        public Nullable<int> ProvincialZipCodeID { get; set; }
        public string TelephoneNo { get; set; }
        public string ProvincialTelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Birthplace { get; set; }
        public string CivilStatus { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Spouse { get; set; }
        public string SpouseOccupation { get; set; }
        public Nullable<int> Children { get; set; }
        public string Child1 { get; set; }
        public string Child2 { get; set; }
        public string Child3 { get; set; }
        public string Child4 { get; set; }
        public string Child5 { get; set; }
        public string OtherChild { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string TaxStatus { get; set; }
        public string TIN { get; set; }
        public string SSS { get; set; }
        public string PAG_IBIG { get; set; }
        public string PhilHealth { get; set; }
        public string CedulaNo { get; set; }
        public string CedulaDate { get; set; }
        public string CedulaPlace { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> Archive { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> NewDeptID { get; set; }
        public string NameSuffix { get; set; }
        public string IDCode { get; set; }
        public string IDCode2 { get; set; }
        public string BankAccountNo { get; set; }
        public Nullable<bool> IsResigned { get; set; }
        public string MiddleInitial { get; set; }
        public string Suffix { get; set; }
        public Nullable<bool> IsBdayHidden { get; set; }
        public Nullable<bool> GreetInSocialMedia { get; set; }
        public string LastName256 { get; set; }
        public string FirstName256 { get; set; }
        public string MiddleName256 { get; set; }
        public string NickName256 { get; set; }
        public string ResidentialAddress256 { get; set; }
        public string ProvincialAddress256 { get; set; }
        public string TelephoneNo256 { get; set; }
        public string ProvincialTelephoneNo256 { get; set; }
        public string MobileNo256 { get; set; }
        public string PrimaryEmail256 { get; set; }
        public string SecondaryEmail256 { get; set; }
        public string Sex256 { get; set; }
        public Nullable<System.DateTime> BirthDay256 { get; set; }
        public string BirthPlace256 { get; set; }
        public string CivilStatus256 { get; set; }
        public string FatherName256 { get; set; }
        public string MotherName256 { get; set; }
        public string Spouse256 { get; set; }
        public string ChildOne256 { get; set; }
        public string ChildTwo256 { get; set; }
        public string ChildThree256 { get; set; }
        public string ChildFour256 { get; set; }
        public string ChildFive256 { get; set; }
        public string OtherChild256 { get; set; }
        public string Nationality256 { get; set; }
        public string Religion256 { get; set; }
        public string TaxStatus256 { get; set; }
        public string TIN256 { get; set; }
        public string SSS256 { get; set; }
        public string PagIbig256 { get; set; }
        public string PhilHealth256 { get; set; }
        public string CedulaNo256 { get; set; }
        public string BankAccountNo256 { get; set; }
        public string MiddleInitial256 { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faculty> Faculty { get; set; }
        public virtual AcademicDepartment AcademicDepartment { get; set; }
    }
}
