//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FeeName()
        {
            this.DiscountTypeDetail = new HashSet<DiscountTypeDetail>();
            this.Fee = new HashSet<Fee>();
        }
    
        public int FeeNameID { get; set; }
        public string FeeName1 { get; set; }
        public string FeeCategory { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> EducLevelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountTypeDetail> DiscountTypeDetail { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fee { get; set; }
    }
}
