//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeLevel
    {
        public int GradeLevelId { get; set; }
        public string GradeLevelName { get; set; }
        public Nullable<int> EducationalLevelId { get; set; }
        public Nullable<int> SectionGradeYear { get; set; }
    }
}
