//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedSOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssuedSOA()
        {
            this.Payment = new HashSet<Payment>();
            this.IssuedSOADetail = new HashSet<IssuedSOADetail>();
        }
    
        public long SOAID { get; set; }
        public int StudentID { get; set; }
        public Nullable<System.DateTime> IssuanceDate { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public string SOANo { get; set; }
        public string SOANo2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Period Period { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuedSOADetail> IssuedSOADetail { get; set; }
    }
}
