//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedSOADetail
    {
        public long SOADetailID { get; set; }
        public Nullable<long> SOAID { get; set; }
        public Nullable<int> PaycodeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual IssuedSOA IssuedSOA { get; set; }
        public virtual Paycode Paycode { get; set; }
    }
}
