//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginalStudentSchedule
    {
        public int ID { get; set; }
        public int ScheduleID { get; set; }
        public int StudentSectionID { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Student_Section Student_Section { get; set; }
    }
}
