//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paycode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paycode()
        {
            this.AssessmentPaymentDate = new HashSet<AssessmentPaymentDate>();
            this.AssessmentPaymentDate_ReAss = new HashSet<AssessmentPaymentDate_ReAss>();
            this.IssuedSOADetail = new HashSet<IssuedSOADetail>();
            this.PaymentDetails = new HashSet<PaymentDetails>();
            this.PaySchedule = new HashSet<PaySchedule>();
        }
    
        public int PaycodeID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Amount { get; set; }
        public bool Active { get; set; }
        public bool TuitionRelated { get; set; }
        public Nullable<int> COANo { get; set; }
        public Nullable<int> SubCOANo { get; set; }
        public Nullable<bool> IsRegistrar { get; set; }
        public Nullable<bool> IsRegistrarOnline { get; set; }
        public Nullable<bool> ForBankPosting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentPaymentDate> AssessmentPaymentDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentPaymentDate_ReAss> AssessmentPaymentDate_ReAss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuedSOADetail> IssuedSOADetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaySchedule> PaySchedule { get; set; }
        public virtual ChartOfAccounts ChartOfAccounts { get; set; }
        public virtual SubChartOfAccounts SubChartOfAccounts { get; set; }
    }
}
