//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paymode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paymode()
        {
            this.AssessmentPaymentDate = new HashSet<AssessmentPaymentDate>();
            this.Tuition = new HashSet<Tuition>();
            this.PaySchedule = new HashSet<PaySchedule>();
            this.Student_Section = new HashSet<Student_Section>();
            this.Student_Section_ReAss = new HashSet<Student_Section_ReAss>();
            this.StudentSectionReAssessment = new HashSet<StudentSectionReAssessment>();
        }
    
        public int PaymodeID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Elem { get; set; }
        public Nullable<bool> JHS { get; set; }
        public Nullable<bool> SHS { get; set; }
        public Nullable<bool> College { get; set; }
        public Nullable<bool> Masteral { get; set; }
        public Nullable<bool> Doctoral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentPaymentDate> AssessmentPaymentDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tuition> Tuition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaySchedule> PaySchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Section> Student_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Section_ReAss> Student_Section_ReAss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSectionReAssessment> StudentSectionReAssessment { get; set; }
    }
}
