//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDefaultPeriod
    {
        public int EducationalLevelId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> ReservationPeriodId { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Period Period1 { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
    }
}
