//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Adjustment = new HashSet<Adjustment>();
            this.BackAccount = new HashSet<BackAccount>();
            this.BackAccountPayment = new HashSet<BackAccountPayment>();
            this.PaymentDetails = new HashSet<PaymentDetails>();
        }
    
        public int PaymentID { get; set; }
        public string ORNo { get; set; }
        public int CashierID { get; set; }
        public byte[] Datestamp { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Bank { get; set; }
        public Nullable<double> CheckAmount { get; set; }
        public string CheckNo { get; set; }
        public Nullable<int> SemID { get; set; }
        public string Branch { get; set; }
        public Nullable<int> EducLevel { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<int> OtherClientID { get; set; }
        public Nullable<long> SOAID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public string Remarks { get; set; }
        public string OrNoBankDeposit { get; set; }
        public Nullable<System.DateTime> OrIssuedDate { get; set; }
        public Nullable<int> OrIssuedCashierID { get; set; }
        public Nullable<System.DateTime> BankDate { get; set; }
        public Nullable<int> CCTransactionID { get; set; }
        public Nullable<int> DPTransactionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccount> BackAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccountPayment> BackAccountPayment { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual IssuedSOA IssuedSOA { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }
        public virtual Student Student { get; set; }
    }
}
