//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySchedule
    {
        public int PaySchedule1 { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> PaycodeID { get; set; }
        public Nullable<int> PaymodeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Paycode Paycode { get; set; }
        public virtual Paymode Paymode { get; set; }
        public virtual Period Period { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
    }
}
