//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostedQneJournalDetail
    {
        public int PostedQneJournalDetailId { get; set; }
        public Nullable<int> PostedQneJournalId { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Project { get; set; }
        public string Id { get; set; }
    
        public virtual PostedQneJournal PostedQneJournal { get; set; }
    }
}
