//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QnePostingLog
    {
        public int Id { get; set; }
        public System.DateTime DatePosted { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string JournalEntryType { get; set; }
        public string PostedBy { get; set; }
        public bool IsSuccessful { get; set; }
    }
}
