//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetails>();
            this.AssessmentSchedule = new HashSet<AssessmentSchedule>();
            this.AssessmentSchedule_ReAss = new HashSet<AssessmentSchedule_ReAss>();
            this.StudentSchedule = new HashSet<StudentSchedule>();
            this.OriginalStudentSchedule = new HashSet<OriginalStudentSchedule>();
        }
    
        public int ScheduleID { get; set; }
        public string Days { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public int SubjectID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> ReservedSlot { get; set; }
        public Nullable<int> MaxSlot { get; set; }
        public Nullable<int> ScheduleStatusID { get; set; }
        public Nullable<int> SectionID2 { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> ClassroomId { get; set; }
        public string EnrollmentCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetails> AdjustmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSchedule> AssessmentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSchedule_ReAss> AssessmentSchedule_ReAss { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchedule> StudentSchedule { get; set; }
        public virtual ScheduleStatus ScheduleStatus { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OriginalStudentSchedule> OriginalStudentSchedule { get; set; }
    }
}
