//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.Others = new HashSet<Others>();
            this.Schedule = new HashSet<Schedule>();
            this.Schedule1 = new HashSet<Schedule>();
            this.Student_Section_ReAss = new HashSet<Student_Section_ReAss>();
            this.Student_Section = new HashSet<Student_Section>();
            this.StudentSectionReAssessment = new HashSet<StudentSectionReAssessment>();
        }
    
        public int SectionID { get; set; }
        public string SectionName { get; set; }
        public short GradeYear { get; set; }
        public int PeriodID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> BlockSectionID { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Others> Others { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Section_ReAss> Student_Section_ReAss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Section> Student_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSectionReAssessment> StudentSectionReAssessment { get; set; }
    }
}
