//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLog
    {
        public int SMSID { get; set; }
        public string Message { get; set; }
        public string MobileNo { get; set; }
        public string TypeofSystem { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<int> ApplicationNo { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> StudentID { get; set; }
    }
}
