//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificFee
    {
        public int SpecificFeeId { get; set; }
        public Nullable<int> FeeId { get; set; }
    
        public virtual Fee Fee { get; set; }
    }
}
