//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.BackAccount = new HashSet<BackAccount>();
            this.Discount = new HashSet<Discount>();
            this.DMCM = new HashSet<DMCM>();
            this.IssuedSOA = new HashSet<IssuedSOA>();
            this.Payment = new HashSet<Payment>();
            this.Promissory = new HashSet<Promissory>();
            this.Student_Curriculum = new HashSet<Student_Curriculum>();
            this.Student_Section = new HashSet<Student_Section>();
        }
    
        public int StudentID { get; set; }
        public string StudentNo { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> YearEntry { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public byte[] Photo { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string LandlineNo { get; set; }
        public string MobileNo { get; set; }
        public string CivilStatus { get; set; }
        public string Religion { get; set; }
        public string FatherName { get; set; }
        public string FatherContact { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherEmployer { get; set; }
        public string FatherEmail { get; set; }
        public string MotherName { get; set; }
        public string MotherContact { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherEmployer { get; set; }
        public string MotherEmail { get; set; }
        public string GuardianName { get; set; }
        public string GuardianAddress { get; set; }
        public string RelationshipToGuardian { get; set; }
        public string GuardianContactNo { get; set; }
        public string FormerSchool { get; set; }
        public string FormerSchoolAddress { get; set; }
        public string GraduationYear { get; set; }
        public Nullable<double> GPA { get; set; }
        public string HonorsReceived { get; set; }
        public string SchoolLastAttended { get; set; }
        public string SchoolLastAttendedCourse { get; set; }
        public string Encoder { get; set; }
        public Nullable<System.DateTime> DateEnconded { get; set; }
        public string ContactNo { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string BDORefNo { get; set; }
        public string IDCode { get; set; }
        public string IDCode2 { get; set; }
        public string EntranceData { get; set; }
        public string SO_Number { get; set; }
        public Nullable<System.DateTime> SO_Date { get; set; }
        public string SO_Serial { get; set; }
        public string Birthplace { get; set; }
        public string EmailAddress { get; set; }
        public string Age { get; set; }
        public string IntermediateSchool { get; set; }
        public string IntermediateSchoolGradYear { get; set; }
        public string LRN { get; set; }
        public string ElementarySchool { get; set; }
        public string ElementarySchoolGradYear { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> NonGMCIssuance { get; set; }
        public string SeniorHighSchoolName { get; set; }
        public string SeniorHighSchoolStrand { get; set; }
        public string SeniorHighSchoolGradYear { get; set; }
        public string MiddleInitial { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZipID { get; set; }
        public string Address2 { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> EscStudentID { get; set; }
        public string EscStudentNumber { get; set; }
        public string QvaNo { get; set; }
        public Nullable<int> StudentApplicationId { get; set; }
        public string SerialNo { get; set; }
        public string LastName256 { get; set; }
        public string FirstName256 { get; set; }
        public string MiddleName256 { get; set; }
        public string Address256 { get; set; }
        public string Nationality256 { get; set; }
        public string Gender256 { get; set; }
        public Nullable<System.DateTime> Birthday256 { get; set; }
        public string City256 { get; set; }
        public string Province256 { get; set; }
        public string PostalCode256 { get; set; }
        public string LandLine256 { get; set; }
        public string MobileNo256 { get; set; }
        public string CivilStatus256 { get; set; }
        public string Religion256 { get; set; }
        public string FatherName256 { get; set; }
        public string FatherContact256 { get; set; }
        public string FatherOccupation256 { get; set; }
        public string FatherEmployer256 { get; set; }
        public string FatherEmail256 { get; set; }
        public string MotherName256 { get; set; }
        public string MotherContact256 { get; set; }
        public string MotherOccupation256 { get; set; }
        public string MotherEmployer256 { get; set; }
        public string MotherEmail256 { get; set; }
        public string GuardianName256 { get; set; }
        public string GuardianAddress256 { get; set; }
        public string GuardianContactNo256 { get; set; }
        public string FormerSchool256 { get; set; }
        public string FormerSchoolAddress256 { get; set; }
        public string SchoolLastAttended256 { get; set; }
        public string ContactNo256 { get; set; }
        public string EmailAddress256 { get; set; }
        public string LRN256 { get; set; }
        public string Adddress256 { get; set; }
    
        public virtual ARMessage ARMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccount> BackAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMCM> DMCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssuedSOA> IssuedSOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promissory> Promissory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Curriculum> Student_Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Section> Student_Section { get; set; }
    }
}
