//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Section()
        {
            this.Adjustment = new HashSet<Adjustment>();
            this.ARMessage = new HashSet<ARMessage>();
            this.Assessment = new HashSet<Assessment>();
            this.AssessmentPaymentDate = new HashSet<AssessmentPaymentDate>();
            this.AssessmentSchedule = new HashSet<AssessmentSchedule>();
            this.BackAccount = new HashSet<BackAccount>();
            this.PaymentDetails = new HashSet<PaymentDetails>();
            this.Promissory = new HashSet<Promissory>();
            this.StudentSchedule = new HashSet<StudentSchedule>();
            this.OriginalStudentSchedule = new HashSet<OriginalStudentSchedule>();
            this.StudentSectionReAssessment = new HashSet<StudentSectionReAssessment>();
        }
    
        public int Student_SectionID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> PaymodeID { get; set; }
        public Nullable<bool> NewStatus { get; set; }
        public Nullable<System.DateTime> EnlistmentDate { get; set; }
        public string EncodedBy { get; set; }
        public Nullable<System.DateTime> ValidationDate { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<double> TuitionFee { get; set; }
        public Nullable<double> MiscFee { get; set; }
        public Nullable<double> SuppFee { get; set; }
        public Nullable<double> LabFee { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public Nullable<double> SecondPayment { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string AssessedBy { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<int> StudentStatus { get; set; }
        public Nullable<int> SectionID2 { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> OnlineDateEncoded { get; set; }
        public Nullable<int> NoOfPayment { get; set; }
        public Nullable<bool> WillAvailModule { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARMessage> ARMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assessment> Assessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentPaymentDate> AssessmentPaymentDate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSchedule> AssessmentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackAccount> BackAccount { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetails> PaymentDetails { get; set; }
        public virtual Paymode Paymode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promissory> Promissory { get; set; }
        public virtual Section Section { get; set; }
        public virtual StudentStatus StudentStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSchedule> StudentSchedule { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OriginalStudentSchedule> OriginalStudentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSectionReAssessment> StudentSectionReAssessment { get; set; }
    }
}
