//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSectionReAssessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentSectionReAssessment()
        {
            this.AssessmentPaymentDate_ReAss = new HashSet<AssessmentPaymentDate_ReAss>();
            this.AssessmentSchedule_ReAss = new HashSet<AssessmentSchedule_ReAss>();
            this.ReAssessment = new HashSet<ReAssessment>();
        }
    
        public int StudentSectionReAssessmentID { get; set; }
        public int Student_SectionID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> PaymodeID { get; set; }
        public bool NewStatus { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public Nullable<System.DateTime> DatePrinted { get; set; }
        public int Status { get; set; }
        public Nullable<double> TuitionFee { get; set; }
        public Nullable<double> MiscFee { get; set; }
        public Nullable<double> SuppFee { get; set; }
        public Nullable<double> LabFee { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> DownPayment { get; set; }
        public Nullable<double> SecondPayment { get; set; }
        public Nullable<double> Credit { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string AssessedBy { get; set; }
        public bool Locked { get; set; }
        public Nullable<int> StudentStatus { get; set; }
        public Nullable<int> SectionID2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentPaymentDate_ReAss> AssessmentPaymentDate_ReAss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSchedule_ReAss> AssessmentSchedule_ReAss { get; set; }
        public virtual Curriculum Curriculum { get; set; }
        public virtual Paymode Paymode { get; set; }
        public virtual Student_Section Student_Section { get; set; }
        public virtual Section Section { get; set; }
        public virtual StudentStatus StudentStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReAssessment> ReAssessment { get; set; }
    }
}
