//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubChartOfAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubChartOfAccounts()
        {
            this.DiscountCategory = new HashSet<DiscountCategory>();
            this.DiscountType = new HashSet<DiscountType>();
            this.DMCM = new HashSet<DMCM>();
            this.EducationalLevel = new HashSet<EducationalLevel>();
            this.Paycode = new HashSet<Paycode>();
            this.Fee = new HashSet<Fee>();
        }
    
        public int SubAcctID { get; set; }
        public string SubAcctNo { get; set; }
        public string SubbAcctName { get; set; }
        public Nullable<int> AcctID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> PayeeID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string QNEAccountCode { get; set; }
    
        public virtual QNEGLAccount QNEGLAccount { get; set; }
        public virtual ChartOfAccounts ChartOfAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountCategory> DiscountCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountType> DiscountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMCM> DMCM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationalLevel> EducationalLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paycode> Paycode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fee> Fee { get; set; }
    }
}
