//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.AssessmentSchedule = new HashSet<AssessmentSchedule>();
            this.Lab = new HashSet<Lab>();
            this.Schedule = new HashSet<Schedule>();
            this.Subject1 = new HashSet<Subject>();
            this.Others = new HashSet<Others>();
        }
    
        public int SubjectID { get; set; }
        public string SubjectCode { get; set; }
        public string Description { get; set; }
        public double Units { get; set; }
        public Nullable<byte> S_CODE { get; set; }
        public Nullable<byte> N_CODE { get; set; }
        public Nullable<int> EducLevelID { get; set; }
        public Nullable<int> IndexKey { get; set; }
        public Nullable<bool> IsTuition { get; set; }
        public Nullable<bool> NAcad { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<double> NoOfHours { get; set; }
        public Nullable<int> MainSubjectID { get; set; }
        public Nullable<bool> IsOneYearComp { get; set; }
        public Nullable<bool> IsComponent { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public Nullable<bool> CanBeIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentSchedule> AssessmentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lab> Lab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subject1 { get; set; }
        public virtual Subject Subject2 { get; set; }
        public virtual EducationalLevel EducationalLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Others> Others { get; set; }
    }
}
