//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLAccounts()
        {
            this.JournalDetails = new HashSet<JournalDetails>();
            this.ReceiptDetails = new HashSet<ReceiptDetails>();
            this.Receipts = new HashSet<Receipts>();
            this.Receipts1 = new HashSet<Receipts>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string GLAccountCode { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<int> SpecialAccountId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> GSTTypeId { get; set; }
        public string Description { get; set; }
        public string DRCR { get; set; }
        public Nullable<bool> IsCreditCard { get; set; }
        public bool IsActive { get; set; }
        public string GSTGroup { get; set; }
        public Nullable<bool> IsRevaluation { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsSubAccount { get; set; }
        public string BankAccountNo { get; set; }
        public string GSTMSICCode { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public string SAC { get; set; }
        public int RowIndex { get; set; }
        public Nullable<bool> HasChildInCoa { get; set; }
        public Nullable<bool> IncludeInCashFlowForecastAdvisor { get; set; }
        public string SSTTariffCode { get; set; }
        public Nullable<int> TariffCodeId { get; set; }
        public Nullable<System.Guid> ATCCodeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetails> JournalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetails> ReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts1 { get; set; }
    }
}
