//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journals()
        {
            this.JournalDetails = new HashSet<JournalDetails>();
            this.JournalDetails1 = new HashSet<JournalDetails>();
        }
    
        public System.Guid Id { get; set; }
        public string JournalCode { get; set; }
        public System.DateTime JournalDate { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<decimal> TotalDebit { get; set; }
        public Nullable<decimal> TotalCredit { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<decimal> GSTRate { get; set; }
        public Nullable<bool> IsRevaluationDR { get; set; }
        public Nullable<bool> IsRevaluationCR { get; set; }
        public Nullable<bool> IsRevaluationGL { get; set; }
        public Nullable<bool> IsBadDebtRelief { get; set; }
        public Nullable<bool> IsBadDebtRecovery { get; set; }
        public Nullable<bool> IsUnpaidPurchase { get; set; }
        public Nullable<bool> IsPaymentForUnpaidPurchase { get; set; }
        public Nullable<int> JournalEntryType { get; set; }
        public Nullable<bool> IsTaxInclusiveOnly { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<bool> IsImportedServicePosted { get; set; }
        public int RowIndex { get; set; }
        public Nullable<System.DateTime> ForecastDueDate { get; set; }
        public Nullable<decimal> ReverseRate { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CostCentreId { get; set; }
        public Nullable<bool> IsSSTBadDebt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetails> JournalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetails> JournalDetails1 { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
