//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JournalDetails()
        {
            this.JournalDetails1 = new HashSet<JournalDetails>();
            this.JournalDetails11 = new HashSet<JournalDetails>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid JournalId { get; set; }
        public int Pos { get; set; }
        public Nullable<System.Guid> GLAccountId { get; set; }
        public string Description { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> GSTType { get; set; }
        public string GSTGroup { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> GSTTaxAmount { get; set; }
        public Nullable<decimal> TaxablePurchases { get; set; }
        public Nullable<decimal> TaxableSales { get; set; }
        public Nullable<decimal> TaxablePurchase { get; set; }
        public Nullable<int> CostCentreId { get; set; }
        public Nullable<decimal> DebitLocal { get; set; }
        public Nullable<decimal> CreditLocal { get; set; }
        public string Note { get; set; }
        public string ItemTypeCode { get; set; }
        public Nullable<System.Guid> TaxCodeId { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<int> TaxClass { get; set; }
        public string TaxClassValue { get; set; }
        public Nullable<decimal> TaxDebit { get; set; }
        public Nullable<decimal> TaxDebitLocal { get; set; }
        public Nullable<decimal> TaxCredit { get; set; }
        public Nullable<decimal> TaxCreditLocal { get; set; }
        public Nullable<decimal> NetDebit { get; set; }
        public Nullable<decimal> NetCredit { get; set; }
        public Nullable<decimal> NetDebitLocal { get; set; }
        public Nullable<decimal> NetCreditLocal { get; set; }
        public Nullable<bool> IsOutputTax { get; set; }
        public Nullable<System.Guid> BDJournalDetailId { get; set; }
        public Nullable<System.Guid> BDInvoiceDetailId { get; set; }
        public Nullable<System.Guid> BDARDNDetailId { get; set; }
        public Nullable<System.Guid> BDBillDetailId { get; set; }
        public Nullable<System.Guid> BDAPDNDetailId { get; set; }
        public Nullable<System.Guid> RecoveredJournalDetailId { get; set; }
        public string TaxClassValueRef { get; set; }
        public Nullable<decimal> TaxExclusiveDebit { get; set; }
        public Nullable<decimal> TaxExclusiveCredit { get; set; }
        public Nullable<decimal> TaxExclusiveDebitLocal { get; set; }
        public Nullable<decimal> TaxExclusiveCreditLocal { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<System.Guid> BDPastInvoiceId { get; set; }
        public Nullable<System.Guid> BDPastARDNId { get; set; }
        public Nullable<System.Guid> BDPastBillId { get; set; }
        public Nullable<System.Guid> BDPastAPDNId { get; set; }
        public Nullable<System.Guid> BDBillId { get; set; }
        public Nullable<System.Guid> GLBIRClsInfo { get; set; }
        public Nullable<System.Guid> PaymentReceiptInfoId { get; set; }
        public Nullable<decimal> SgstDebit { get; set; }
        public Nullable<decimal> CgstDebit { get; set; }
        public Nullable<decimal> IgstDebit { get; set; }
        public Nullable<decimal> SgstDebitLocal { get; set; }
        public Nullable<decimal> CgstDebitLocal { get; set; }
        public Nullable<decimal> IgstDebitLocal { get; set; }
        public Nullable<decimal> SgstCredit { get; set; }
        public Nullable<decimal> CgstCredit { get; set; }
        public Nullable<decimal> IgstCredit { get; set; }
        public Nullable<decimal> SgstCreditLocal { get; set; }
        public Nullable<decimal> CgstCreditLocal { get; set; }
        public Nullable<decimal> IgstCreditLocal { get; set; }
        public int RowIndex { get; set; }
        public Nullable<int> TariffCodeId { get; set; }
        public Nullable<System.Guid> RecoveredPastInvoiceId { get; set; }
        public Nullable<System.Guid> BDJournalId { get; set; }
        public Nullable<System.Guid> BDInvoiceId { get; set; }
        public Nullable<System.Guid> BDARDNId { get; set; }
        public Nullable<System.Guid> BDAPDNId { get; set; }
        public Nullable<bool> IsCreditable { get; set; }
        public Nullable<System.Guid> WTaxCode { get; set; }
        public Nullable<decimal> WTaxDebit { get; set; }
        public Nullable<decimal> WTaxCredit { get; set; }
        public Nullable<bool> IsDeferredVAT { get; set; }
        public Nullable<System.Guid> ServiceTaxCode { get; set; }
        public Nullable<System.DateTime> ServicePostingDate { get; set; }
        public Nullable<decimal> ServiceTaxAmount { get; set; }
        public Nullable<decimal> LocalOneCentsDiff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetails> JournalDetails1 { get; set; }
        public virtual JournalDetails JournalDetails2 { get; set; }
        public virtual Journals Journals { get; set; }
        public virtual Journals Journals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetails> JournalDetails11 { get; set; }
        public virtual JournalDetails JournalDetails3 { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual GLAccounts GLAccounts { get; set; }
    }
}
