//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QNEDBEntities : DbContext
    {
        public QNEDBEntities()
            : base("name=QNEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JournalDetails> JournalDetails { get; set; }
        public virtual DbSet<Journals> Journals { get; set; }
        public virtual DbSet<GLAccounts> GLAccounts { get; set; }
        public virtual DbSet<ReceiptDetails> ReceiptDetails { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
    }
}
