//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.JournalDetails = new HashSet<JournalDetails>();
            this.Journals = new HashSet<Journals>();
            this.Projects1 = new HashSet<Projects>();
            this.ReceiptDetails = new HashSet<ReceiptDetails>();
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int Id { get; set; }
        public string ProjectCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ProjectedEndDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> ContractSum { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public string Header { get; set; }
        public string CompanyName { get; set; }
        public string CompanyName2 { get; set; }
        public string RegNo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string TradeName { get; set; }
        public string ZipCode { get; set; }
        public string ContactPerson { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string GSTRegNo { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string HomePage { get; set; }
        public string BusinessNature { get; set; }
        public string Signatory { get; set; }
        public string GSTApprovalNo { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.Guid> CBIRClassification { get; set; }
        public Nullable<System.Guid> RDOData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JournalDetails> JournalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journals> Journals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects1 { get; set; }
        public virtual Projects Projects2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetails> ReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
