//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetails
    {
        public System.Guid Id { get; set; }
        public System.Guid ReceiptId { get; set; }
        public int Pos { get; set; }
        public Nullable<System.Guid> GLAccountId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<int> WTaxTypeId { get; set; }
        public Nullable<decimal> WTaxAmount { get; set; }
        public Nullable<int> GSTTypeId { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> TaxableSales { get; set; }
        public Nullable<int> CostCentreId { get; set; }
        public Nullable<decimal> AmountLocal { get; set; }
        public string Note { get; set; }
        public string ItemTypeCode { get; set; }
        public Nullable<System.Guid> TaxCodeId { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<int> TaxClass { get; set; }
        public string TaxClassValue { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxAmountLocal { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> NetAmountLocal { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
        public Nullable<decimal> SubAmountLocal { get; set; }
        public string TaxClassValueRef { get; set; }
        public Nullable<decimal> TaxExclusiveAmount { get; set; }
        public Nullable<decimal> TaxExclusiveAmountLocal { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<System.Guid> WTaxCode { get; set; }
        public Nullable<decimal> WTaxRate { get; set; }
        public Nullable<decimal> WTaxAmountLocal { get; set; }
        public Nullable<System.Guid> PaymentReceiptInfoId { get; set; }
        public Nullable<System.Guid> GLBIRClsInfo { get; set; }
        public int RowIndex { get; set; }
        public Nullable<int> TariffCodeId { get; set; }
        public Nullable<System.Guid> WVatCode { get; set; }
        public Nullable<decimal> WVatRate { get; set; }
        public Nullable<decimal> WVatAmount { get; set; }
        public Nullable<decimal> WVatAmountLocal { get; set; }
        public Nullable<System.DateTime> ServicePostingDate { get; set; }
        public Nullable<System.Guid> ATCCodeId { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Receipts Receipts { get; set; }
        public virtual GLAccounts GLAccounts { get; set; }
    }
}
