//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARManila.Models.QneDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.ReceiptDetails = new HashSet<ReceiptDetails>();
        }
    
        public System.Guid Id { get; set; }
        public string ReceiptCode { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<System.Guid> GLAccountId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<System.Guid> DebtorId { get; set; }
        public string DebtorName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<bool> IsDetailForGLPosting { get; set; }
        public Nullable<int> GSTTypeId { get; set; }
        public Nullable<decimal> GSTTaxRate { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> GSTTaxAmount { get; set; }
        public Nullable<decimal> TotalAmountLocal { get; set; }
        public Nullable<decimal> GSTAmountLocal { get; set; }
        public Nullable<decimal> WTaxAmount { get; set; }
        public Nullable<bool> IsPostDatedCheque { get; set; }
        public Nullable<System.DateTime> ChequePreparedDate { get; set; }
        public Nullable<System.DateTime> ChequeReceivedDate { get; set; }
        public Nullable<bool> IsBouncedCheque { get; set; }
        public Nullable<System.DateTime> BouncedChequeDate { get; set; }
        public Nullable<bool> IsMultiPayment { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CostCentreId { get; set; }
        public Nullable<decimal> TaxTotalAmount { get; set; }
        public Nullable<decimal> TaxTotalAmountLocal { get; set; }
        public Nullable<decimal> NetTotalAmount { get; set; }
        public Nullable<decimal> NetTotalAmountLocal { get; set; }
        public Nullable<decimal> SubtotalAmount { get; set; }
        public Nullable<decimal> SubtotalAmountLocal { get; set; }
        public Nullable<decimal> BankChargesAmountLocal { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public Nullable<System.Guid> BankCharges { get; set; }
        public Nullable<System.Guid> PaymentReceiptInfoId { get; set; }
        public Nullable<decimal> TaxExclusiveTotalAmount { get; set; }
        public Nullable<decimal> TaxExclusiveTotalAmountLocal { get; set; }
        public Nullable<bool> IsDepositDoc { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<bool> IsTaxInclusiveOnly { get; set; }
        public Nullable<System.Guid> RoundingAdjustmentAccount { get; set; }
        public Nullable<decimal> RoundingAdjustment { get; set; }
        public Nullable<decimal> RoundingAdjustmentLocal { get; set; }
        public Nullable<bool> IsRounding { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<System.Guid> TaxCodeId { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> WTaxTotalAmount { get; set; }
        public Nullable<decimal> WTaxTotalAmountLocal { get; set; }
        public Nullable<bool> PostGLDescription { get; set; }
        public Nullable<bool> UseMultiPayment { get; set; }
        public Nullable<decimal> UnmatchAmount { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostLocal { get; set; }
        public Nullable<System.DateTime> ClearedDate { get; set; }
        public int RowIndex { get; set; }
        public Nullable<System.Guid> PaymentMethodMaintenanceId { get; set; }
        public Nullable<decimal> TotalCashAmount { get; set; }
        public Nullable<decimal> TotalChequeAmount { get; set; }
        public Nullable<decimal> ReverseRate { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public string Ref3 { get; set; }
        public string Ref4 { get; set; }
        public string Ref5 { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public string Remark5 { get; set; }
        public Nullable<decimal> WVatTotalAmount { get; set; }
        public Nullable<decimal> WVatTotalAmountLocal { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<bool> IsESales { get; set; }
        public Nullable<decimal> TotalWtaxAmount { get; set; }
        public Nullable<bool> HasDeposit { get; set; }
        public Nullable<System.DateTime> WTaxDate { get; set; }
    
        public virtual Projects Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetails> ReceiptDetails { get; set; }
        public virtual GLAccounts GLAccounts { get; set; }
        public virtual GLAccounts GLAccounts1 { get; set; }
    }
}
